"""add thumb url for posts

Revision ID: 420d76060a1d
Revises: 4d82953329b8
Create Date: 2019-05-20 18:48:39.455359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420d76060a1d'
down_revision = '4d82953329b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumb_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'thumb_url')
    # ### end Alembic commands ###
